config/routes.rb
Rails.application.routes.draw do

  resources :airlines
  resources :airports
  resources :routes
  
  root 'welcome#index'
end

app/models/airline.rb
class Airline < ApplicationRecord
end

app/models/airport.rb
class Airport < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/route.rb
class Route < ApplicationRecord
end

app/controllers/airlines_controller.rb
class AirlinesController < ApplicationController

  def index
    @airlines = Airline.all
  end

end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController

  def index
    @airports = Airport.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController

  def index
    @routes = Route.all
    ###How to put in logic to access airline?
  end

  def show
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/airline_helper.rb
module AirlineHelper
end

app/helpers/airport_helper.rb
module AirportHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/route_helper.rb
module RouteHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/airlines/index.html.erb
<h1 class="page-header">Check out all of the airlines!</h1>

<div class="">
  <%@airlines.each do |airline|%>
  <ul>
    <li>    <%=airline.name%></li>
  </ul>

  <%end%>
</div>

app/views/airports/index.html.erb
<h1 class="page-header">Check out all of the airports!</h1>

<div class="">
  <%@airports.each do |airport|%>
  <ul>
    <li><%=airport.name%></li>
  </ul>
  <%end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beetroot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css?family=Assistant:200|Cormorant+Garamond:300|Cormorant+SC:300|Questrial" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Megrim|Parisienne|Petit+Formal+Script" rel="stylesheet">
    <!-- fonts -->

  </head>

  <body>

    <div class="header" id="header">
      <h1 id="header-name" class="no-decoration"><%=link_to "BeetRoot", root_path%></h1>
    </div>

    <section id="menu">
      <span id="menu-items">
          <p class="menu-item no-decoration"><%=link_to "Airlines", airlines_path, :class=>"menu-link"%></p>
          <p class="menu-item no-decoration"><%=link_to "Airports", airports_path, :class=>"menu-link"%></p>
          <p class="menu-item no-decoration"><%=link_to "Routes", routes_path, :class=>"menu-link"%></p>
      </span>
    </section>

    <%= yield %>
  </body>
</html>

app/views/routes/index.html.erb
<h1 class="page-header">Check out all of the routes!</h1>

<div class="">
  <%@routes.each do |route|%>
    <%airline_id = route.airline_id%>
    <%airline = Airline.find_by_id(airline_id)%>
    <%if airline%>
      <ol>
        <%=airline.name%>
      </ol>
    <%end%>
  <%end%>
</div>

app/views/routes/show.html.erb
<h1>Route#show</h1>
<p>Find me in app/views/route/show.html.erb</p>

app/views/routes/update.html.erb
<h1>Route#update</h1>
<p>Find me in app/views/route/update.html.erb</p>

app/views/welcome/index.html.erb
<h1 class="page-header">Welcome to BeetRoot!</h1>